branches:
  only:
    - use-carma

skip_non_tags: true

environment:
  matrix:
    # Compilation takes 15-25 minutes on AppVeyor servers
    # so the jobs need to be split
    - job_name: "python37-x64-macos-mojave-cp37"
      APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      CIBW_BUILD: "cp37-*"

stack: python 3.7

install:
  - git submodule update --init --recursive
  - python -m pip install cibuildwheel==1.8.0

build_script: | 
  cd python
  python -m cibuildwheel --output-dir wheelhouse
