branches:
  only:
    - use-carma

skip_non_tags: true

environment:
  matrix:
    # Compilation takes 15-25 minutes on AppVeyor servers
    # so the jobs need to be split
    - job_name: "python37-x64-macos-mojave-cp36"
      APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      CIBW_BUILD: "cp36-*"

stack: python 3.7

install: python -m pip install cibuildwheel==1.8.0

build_script: python -m cibuildwheel --output-dir wheelhouse
