# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

L0LearnFit_sparse <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_L0Learn_L0LearnFit_sparse', PACKAGE = 'L0Learn', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

L0LearnFit_dense <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_L0Learn_L0LearnFit_dense', PACKAGE = 'L0Learn', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

L0LearnCV_sparse <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_L0Learn_L0LearnCV_sparse', PACKAGE = 'L0Learn', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

L0LearnCV_dense <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_L0Learn_L0LearnCV_dense', PACKAGE = 'L0Learn', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

cor_matrix <- function(p, base_cor) {
    .Call('_L0Learn_cor_matrix', PACKAGE = 'L0Learn', p, base_cor)
}

R_matrix_column_get_dense <- function(mat, col) {
    .Call('_L0Learn_R_matrix_column_get_dense', PACKAGE = 'L0Learn', mat, col)
}

R_matrix_column_get_sparse <- function(mat, col) {
    .Call('_L0Learn_R_matrix_column_get_sparse', PACKAGE = 'L0Learn', mat, col)
}

R_matrix_rows_get_dense <- function(mat, rows) {
    .Call('_L0Learn_R_matrix_rows_get_dense', PACKAGE = 'L0Learn', mat, rows)
}

R_matrix_rows_get_sparse <- function(mat, rows) {
    .Call('_L0Learn_R_matrix_rows_get_sparse', PACKAGE = 'L0Learn', mat, rows)
}

R_matrix_column_sums_dense <- function(mat) {
    .Call('_L0Learn_R_matrix_column_sums_dense', PACKAGE = 'L0Learn', mat)
}

R_matrix_column_sums_sparse <- function(mat) {
    .Call('_L0Learn_R_matrix_column_sums_sparse', PACKAGE = 'L0Learn', mat)
}

R_matrix_column_dot_dense <- function(mat, col, u) {
    .Call('_L0Learn_R_matrix_column_dot_dense', PACKAGE = 'L0Learn', mat, col, u)
}

R_matrix_column_dot_sparse <- function(mat, col, u) {
    .Call('_L0Learn_R_matrix_column_dot_sparse', PACKAGE = 'L0Learn', mat, col, u)
}

R_matrix_normalize_dense <- function(mat_norm) {
    .Call('_L0Learn_R_matrix_normalize_dense', PACKAGE = 'L0Learn', mat_norm)
}

R_matrix_normalize_sparse <- function(mat_norm) {
    .Call('_L0Learn_R_matrix_normalize_sparse', PACKAGE = 'L0Learn', mat_norm)
}

R_matrix_center_dense <- function(mat, X_normalized, intercept) {
    .Call('_L0Learn_R_matrix_center_dense', PACKAGE = 'L0Learn', mat, X_normalized, intercept)
}

R_matrix_center_sparse <- function(mat, X_normalized, intercept) {
    .Call('_L0Learn_R_matrix_center_sparse', PACKAGE = 'L0Learn', mat, X_normalized, intercept)
}

R_vector_subset <- function(x, indicies) {
    .Call('_L0Learn_R_vector_subset', PACKAGE = 'L0Learn', x, indicies)
}

R_arg_sort <- function(x) {
    .Call('_L0Learn_R_arg_sort', PACKAGE = 'L0Learn', x)
}

R_make_predicitions_dense <- function(X, B, b0) {
    .Call('_L0Learn_R_make_predicitions_dense', PACKAGE = 'L0Learn', X, B, b0)
}

R_make_predicitions_sparse <- function(X, B, b0) {
    .Call('_L0Learn_R_make_predicitions_sparse', PACKAGE = 'L0Learn', X, B, b0)
}

