name: Build

on: 
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.15] # windows-2019, ubuntu-20.04, ]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout l0learn
        uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: Setup Python
        uses: actions/setup-python@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.5.0
        

      - name: Build wheels
        run: |
          cd python
          python -m cibuildwheel --output-dir wheelhouse
        env: 
          CIBW_SKIP: pp*
          CIBW_BEFORE_ALL: cd ../external/carma && mkdir build  && cd build  && cmake -DCARMA_INSTALL_LIB=ON .. && cmake --build . --config Release --target install
          CIBW_BEFORE_ALL_MACOS: brew install armadillo
          CIBW_BEFORE_TEST: "pip install pytest numpy hypothesis"
          CIBW_TEST_COMMAND: "pytest {package}/tests"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
