name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macOS-10.15, windows-2019, ]


    steps:
      - name: Checkout l0learn
        uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.5.0

      - name: Build wheels
        run: |
          cd python
          python -m cibuildwheel --output-dir wheelhouse
        env: 
          CIBW_SKIP: pp* *-win32 *-manylinux_i686
          CIBW_BEFORE_ALL_LINUX: "yum install -y lapack-devel && bash scripts/install_linux_libs.sh"
          CIBW_BEFORE_TEST: "pip install pytest numpy hypothesis"
          CIBW_TEST_COMMAND: "pytest {package}/tests"
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
